// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnxf8i6X2Cvja2jxIUmDkShastnA7hQew',
    appId: '1:719211110711:web:5cdeb62e998d2da0493ab2',
    messagingSenderId: '719211110711',
    projectId: 'chatapp-27c05',
    authDomain: 'chatapp-27c05.firebaseapp.com',
    storageBucket: 'chatapp-27c05.firebasestorage.app',
    measurementId: 'G-KNL0HGGQR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_USbk6o6-v-xbxBmw-Z7pkPZTrdFude0',
    appId: '1:719211110711:android:24a498d677eaf325493ab2',
    messagingSenderId: '719211110711',
    projectId: 'chatapp-27c05',
    storageBucket: 'chatapp-27c05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWnEx_nPAjrvHNfYu2C7Ogx_TuUVSLccU',
    appId: '1:719211110711:ios:f1eca20d7059d00b493ab2',
    messagingSenderId: '719211110711',
    projectId: 'chatapp-27c05',
    storageBucket: 'chatapp-27c05.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWnEx_nPAjrvHNfYu2C7Ogx_TuUVSLccU',
    appId: '1:719211110711:ios:f1eca20d7059d00b493ab2',
    messagingSenderId: '719211110711',
    projectId: 'chatapp-27c05',
    storageBucket: 'chatapp-27c05.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnxf8i6X2Cvja2jxIUmDkShastnA7hQew',
    appId: '1:719211110711:web:44eee859beff601c493ab2',
    messagingSenderId: '719211110711',
    projectId: 'chatapp-27c05',
    authDomain: 'chatapp-27c05.firebaseapp.com',
    storageBucket: 'chatapp-27c05.firebasestorage.app',
    measurementId: 'G-L3MM1N41JX',
  );
}
